import Header from "@/components/header/Header"
import Toast from "@/components/toast/Toast"
import ToastProvider from "@/context/ToastContext"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Taroko Project</title>
      </head>
      
      <body className={inter.className}>
        <ToastProvider>
          <Header />
          {children}
          <Toast />
        </ToastProvider>
      </body>
    </html>
  )
}
